name: arm-no-gil-test

on: [push, pull_request]

# Limit GITHUB_TOKEN permissions
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-24.04-arm64
    container:
      image: quay.io/pypa/manylinux2014_aarch64
    steps:
      - name: Verify Python
        run: python3.14t -c "import sys; print(sys.version)"
