jobs:
  build:
    runs-on: ubuntu-22.04-arm64
    container:
      image: quay.io/pypa/manylinux2014_aarch64
    steps:
      - name: Verify Python
        run: python3.14t -c "import sys; print(sys.version)"
